import './globals.css';
import '../public/static/fonts/pretendardvariable.css';

import { ModalProvider } from '@/providers/home-modal-provider';
import { ToastProvider } from '@/providers/toast-provider';
import { SiteHeader } from '@/components/navbar/site-header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <div className="relative flex flex-col">
          <SiteHeader />
        </div>
        <ToastProvider />
        <ModalProvider />

        {children}
      </body>
    </html>
  );
}
