import './globals.css';
import '../public/static/fonts/pretendardvariable.css';

import Navbar from '@/components/navbar';
import { ModalProvider } from '@/providers/home-modal-provider';
import { ToastProvider } from '@/providers/toast-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <Navbar />
        <ToastProvider />
        <ModalProvider />

        {children}
      </body>
    </html>
  );
}
