import './globals.css';
import '../public/static/fonts/pretendardvariable.css';

import { ToastProvider } from '@/providers/toast-provider';
import { SiteHeader } from '@/components/navbar/site-header';
import { ThemeProvider } from '@/components/theme-provider';
import { CreateAccountProvider } from '@/providers/create-account-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="kr">
      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="relative flex flex-col">
            <SiteHeader />
          </div>

          <ToastProvider />
          <CreateAccountProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
